### ISSUE TITLE
getsockopt Error when trying to join a server.

### ISSUE THREAD

**Issue by M4ximumPizza** [playit-cloud/playit-minecraft-plugin#30]
**What Minecraft Server type and version are you using?**
I have a fabric Minecraft server for 1.21.4 and when the server is fully loaded with playit, it wont let anyone join with the error of getsockopt. My server is whitelisted luckily and the only "players" that can join are random bots trying to connect to the server and are halted by the whitelist security protocol. 

**Expected behavior**
Its supposed to let the player join the world 

This is with version 0.15.26.

![image](https://github.com/user-attachments/assets/5defc197-7ef8-4e2d-b004-e6b4ce5a2ff1)

**Comment by M4ximumPizza** [comment]
Fixed. Dont know what happened but now its fixed.

**Comment by YerDadD** [comment]
Some other users trying to connect to my server are facing this same issue. Not all of them, only some. 

I've run through the normal steps with them of getting them of adjusting their firewall, but no dice.

When they try to connect, the server never sees the request so far as I can tell. I never see it in the Minecraft Server Terminal like I do whenever someone else tries to connect (even if that user fails to connect.)

One user has been able to get around the issue by using a VPN, while the other has failed to. (I even connected using the same VPN as the one that still failed to connect but connected just fine.)

At a bit of a loss on this one, possible to reopen the issue to discuss and test? Or should a new issue be opened.

*Context for My Server*
-Arclight 1.0.6 (Server build that allows bukkit plugins to work alongside Forge mods)
-Minecraft 1.20.1
-Forge 47.3.22
(let me know to provide anything else)

**Comment by M4ximumPizza** [comment]
Reopened!

**Comment by YerDadD** [comment]
I'm hoping this isn't an issue with ISPs and that there is a fix or workaround; though as pointed out in my last comment, all of our troubleshooting steps have failed.

**Comment by M4ximumPizza** [comment]
I was thinking that the server failed to complete a socket handshake or socket operation between the Minecraft client and the tunnel (Playit.gg). Then when the client connects to the server, it has a mismatched handshake which causes it to disconnect.

**Comment by YerDadD** [comment]
> I was thinking that the server failed to complete a socket handshake or socket operation between the Minecraft client and the tunnel (Playit.gg). Then when the client connects to the server, it has a mismatched handshake which causes it to disconnect.

Right, the question becomes the reasoning for the dropped handshake. I've double checked version compatibility. 
-The user's client is exact same java, minecraft, forge, and mod(s) versions that the server is using; so that should be all relevant checks there. 
-User has ensured that all java executable files and operations are allowed in their firewall.

So this 'should' rule out the client, no?

Only thing that throws a wrench in my idea of an ISP block is that the user tried connecting through a known working VPN server, to no avail. So where does this leave it, DNS issue?

**Comment by YerDadD** [comment]
Additional info for this issue. Not sure if it helps:

The log for the user's client when they fail to connect _(the "xx"s strike the address details)_:

>`[01:46:49] [Server Connector #3/ERROR]`: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: getsockopt: xxx.xx.xxx.xx/[xxxx:xxxx:xxx:x:x:x:x:xx]:xxxxx
Caused by: java.net.ConnectException: Connection timed out: getsockopt
        &nbsp;        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        &nbsp;        at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
        &nbsp;        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) ~[?:?]
        &nbsp;        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
        &nbsp;        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
        &nbsp;        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
        &nbsp;        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
        &nbsp;        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
        &nbsp;        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
        &nbsp;        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23123!/:4.1.82.Final]
        &nbsp;        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23123!/:4.1.82.Final]
        &nbsp;        at java.lang.Thread.run(Thread.java:840) ~[?:?]


Anyone got any clue if this points to an issue on the client system, DNS, or an ISP issue?

**Comment by Simonko-912** [comment]
i get the same issue but discordsrv works even tho i cant join using the ip
